# Generated by Django 3.2.7 on 2021-09-26 12:53

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_alter_book_book_published'), ('main', '0003_alter_book_book_published'), ('main', '0004_auto_20210917_2051'), ('main', '0005_auto_20210918_0208'), ('main', '0006_alter_book_book_published'), ('main', '0007_alter_book_book_published'), ('main', '0008_alter_book_book_published'), ('main', '0009_alter_book_book_published'), ('main', '0010_alter_book_book_published'), ('main', '0011_alter_book_book_published'), ('main', '0012_alter_book_book_published'), ('main', '0013_alter_book_book_published'), ('main', '0014_alter_book_book_published'), ('main', '0015_alter_book_book_published'), ('main', '0016_alter_book_book_published'), ('main', '0017_alter_book_book_published'), ('main', '0018_alter_book_book_published'), ('main', '0019_alter_book_book_published'), ('main', '0020_alter_book_book_published'), ('main', '0021_alter_book_book_published'), ('main', '0022_alter_book_book_published'), ('main', '0023_alter_book_book_published'), ('main', '0024_alter_book_book_published'), ('main', '0025_alter_book_book_published'), ('main', '0026_alter_book_book_published'), ('main', '0027_alter_book_book_published'), ('main', '0028_alter_book_book_published'), ('main', '0029_alter_book_book_published'), ('main', '0030_alter_book_book_published'), ('main', '0031_alter_book_book_published'), ('main', '0032_alter_book_book_published'), ('main', '0033_auto_20210919_1750'), ('main', '0034_alter_book_book_published'), ('main', '0035_alter_book_book_published'), ('main', '0036_alter_book_book_published'), ('main', '0037_alter_book_book_published'), ('main', '0038_auto_20210919_2104'), ('main', '0039_alter_book_book_published'), ('main', '0040_alter_book_book_published'), ('main', '0041_auto_20210921_1611'), ('main', '0042_alter_book_book_published'), ('main', '0043_alter_book_book_published'), ('main', '0044_auto_20210921_1643'), ('main', '0045_auto_20210921_1643'), ('main', '0046_alter_book_book_published'), ('main', '0047_alter_book_book_published'), ('main', '0048_alter_book_book_published'), ('main', '0049_alter_book_book_published'), ('main', '0050_delete_book')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=100)),
                ('class_summary', models.CharField(max_length=500)),
                ('class_slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_subject', models.CharField(max_length=100)),
                ('subject_summary', models.CharField(max_length=500)),
                ('subject_slug', models.SlugField(max_length=100)),
                ('student_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentclass', verbose_name='Class')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='StudentChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_chapter', models.CharField(max_length=100)),
                ('chapter_summary', models.CharField(max_length=500)),
                ('chapter_slug', models.SlugField(max_length=100)),
                ('student_subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentsubject', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_section', models.CharField(max_length=100)),
                ('section_summary', models.CharField(max_length=500)),
                ('section_slug', models.SlugField(max_length=100)),
                ('section_text', models.TextField()),
                ('student_chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentchapter', verbose_name='Chapter')),
                ('section_video', models.FileField(blank=True, null=True, upload_to=main.models.StudentSection.user_directory_path)),
                ('section_video_base', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
