# Generated by Django 3.1 on 2021-12-29 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=100)),
                ('class_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('class_slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_subject', models.CharField(max_length=100)),
                ('subject_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('subject_slug', models.SlugField(max_length=100)),
                ('student_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentclass', verbose_name='Class')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='StudentChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_chapter', models.CharField(max_length=100)),
                ('chapter_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('chapter_slug', models.SlugField(max_length=100)),
                ('student_subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentsubject', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_text', models.CharField(max_length=500)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('last_message_seen', models.BooleanField()),
                ('chat_recipients', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Chat Recipients')),
                ('last_message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Message Sender')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_category', models.CharField(max_length=100)),
                ('category_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('category_slug', models.SlugField(max_length=100)),
                ('category_image', models.FileField(upload_to=main.models.StudentCategory.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_title', models.CharField(max_length=500)),
                ('help_text', models.CharField(max_length=5000)),
                ('help_video', models.FileField(blank=True, null=True, upload_to=main.models.HelpSection.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chat', verbose_name='Chat')),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_title', models.CharField(max_length=500)),
                ('notif_text', models.CharField(blank=True, max_length=5000, null=True)),
                ('notif_file', models.FileField(blank=True, null=True, upload_to=main.models.Notification.user_directory_path)),
                ('notif_time', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_content', models.CharField(max_length=100)),
                ('content_text', models.TextField()),
                ('content_time', models.DateTimeField(auto_now_add=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to=main.models.StudentContent.user_directory_path)),
                ('content_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentcategory', verbose_name='Category')),
                ('content_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_section', models.CharField(max_length=100)),
                ('section_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('section_slug', models.SlugField(max_length=100)),
                ('section_text', models.TextField(blank=True, null=True)),
                ('student_chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentchapter', verbose_name='Chapter')),
                ('section_file', models.FileField(blank=True, null=True, upload_to=main.models.StudentSection.user_directory_path)),
                ('section_file_base', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='UploadAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=100)),
                ('audio_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('audio_file', models.FileField(upload_to=main.models.UploadAudio.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Audios',
            },
        ),
        migrations.CreateModel(
            name='UploadFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_text', models.CharField(max_length=5000)),
                ('feed_date', models.DateTimeField(auto_now_add=True)),
                ('feed_file', models.FileField(blank=True, null=True, upload_to=main.models.UploadFeed.user_directory_path)),
                ('feed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Feed',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('file_file', models.FileField(upload_to=main.models.UploadFile.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('image_file', models.FileField(upload_to=main.models.UploadImage.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(upload_to=main.models.UploadVideo.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
