# Generated by Django 3.1 on 2021-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_auto_20211229_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
