# Generated by Django 3.2.7 on 2021-09-16 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 20, 57, 8, 216644), verbose_name='When was this book published?'),
        ),
    ]
