# Generated by Django 3.2.7 on 2021-09-29 15:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0050_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=100)),
                ('audio_summary', models.CharField(max_length=500)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=main.models.UploadAudio.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Audios',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_summary', models.CharField(max_length=500)),
                ('file_file', models.FileField(blank=True, null=True, upload_to=main.models.UploadFile.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_summary', models.CharField(max_length=500)),
                ('image_file', models.FileField(blank=True, null=True, upload_to=main.models.UploadImage.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_summary', models.CharField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=main.models.UploadVideo.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
