# Generated by Django 3.2.7 on 2021-09-17 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_book_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_chapter', models.CharField(max_length=100)),
                ('chapter_summary', models.CharField(max_length=500)),
                ('chapter_slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(max_length=100)),
                ('class_summary', models.CharField(max_length=500)),
                ('class_slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 20, 51, 30, 866925), verbose_name='When was this book published?'),
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_subject', models.CharField(max_length=100)),
                ('subject_summary', models.CharField(max_length=500)),
                ('subject_slug', models.CharField(max_length=100)),
                ('student_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentclass', verbose_name='Class')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_section', models.CharField(max_length=100)),
                ('section_summary', models.CharField(max_length=500)),
                ('section_slug', models.CharField(max_length=100)),
                ('section_text', models.CharField(max_length=1000)),
                ('student_chater', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentchapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AddField(
            model_name='studentchapter',
            name='student_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.studentsubject', verbose_name='Subject'),
        ),
    ]
