# Generated by Django 3.1 on 2021-10-20 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20211020_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_text', models.CharField(max_length=500)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('last_message_seen', models.BooleanField()),
                ('chat_recipients', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Chat Recipients')),
                ('last_message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last Message Sender')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chat', verbose_name='Chat')),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message Sender')),
            ],
        ),
    ]
