# Generated by Django 3.2.7 on 2021-09-17 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210917_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsection',
            old_name='student_chater',
            new_name='student_chapter',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 2, 8, 35, 738433), verbose_name='When was this book published?'),
        ),
    ]
