# Generated by Django 3.1 on 2021-10-24 08:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_title', models.CharField(max_length=500)),
                ('notif_text', models.CharField(max_length=5000)),
                ('notif_file', models.FileField(blank=True, null=True, upload_to=main.models.Notification.user_directory_path)),
            ],
        ),
    ]
