# Generated by Django 3.2.7 on 2021-09-18 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210918_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 12, 46, 20, 884491), verbose_name='When was this book published?'),
        ),
    ]
