# Generated by Django 3.1 on 2021-11-05 05:56

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notification_notif_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_category', models.CharField(max_length=100)),
                ('category_summary', models.CharField(max_length=500)),
                ('category_slug', models.SlugField(max_length=100)),
                ('category_image', models.FileField(upload_to=main.models.StudentCategory.user_directory_path)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StudentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_content', models.CharField(max_length=100)),
                ('content_text', models.TextField()),
                ('content_date', models.DateTimeField(auto_now_add=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to=main.models.StudentContent.user_directory_path)),
                ('content_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.studentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
    ]
