# Generated by Django 3.1 on 2021-11-05 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_studentcontent_content_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontent',
            name='content_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='studentcontent',
            name='content_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
