# Generated by Django 3.1 on 2021-11-13 02:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211105_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_title', models.CharField(max_length=500)),
                ('help_text', models.CharField(max_length=5000)),
                ('help_video', models.FileField(blank=True, null=True, upload_to=main.models.HelpSection.user_directory_path)),
            ],
        ),
    ]
