# Generated by Django 3.1 on 2021-12-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_helpsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='studentcategory',
            name='category_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentchapter',
            name='chapter_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='section_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='section_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadaudio',
            name='audio_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
