# Generated by Django 3.1 on 2021-12-19 06:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211219_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadaudio',
            name='audio_file',
            field=models.FileField(upload_to=main.models.UploadAudio.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_file',
            field=models.FileField(upload_to=main.models.UploadFile.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image_file',
            field=models.FileField(upload_to=main.models.UploadImage.user_directory_path),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_file',
            field=models.FileField(upload_to=main.models.UploadVideo.user_directory_path),
        ),
    ]
