# Generated by Django 3.2.7 on 2021-09-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_book_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 21, 4, 9, 143261), verbose_name='When was this book published?'),
        ),
        migrations.AlterField(
            model_name='studentchapter',
            name='chapter_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='class_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='section_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject_slug',
            field=models.SlugField(max_length=100),
        ),
    ]
