# Generated by Django 3.2.7 on 2021-09-19 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210919_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 21, 12, 13, 488172), verbose_name='When was this book published?'),
        ),
    ]
