# Generated by Django 3.2.7 on 2021-09-21 10:41

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_book_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsection',
            name='section_video',
            field=models.FileField(blank=True, null=True, upload_to=main.models.StudentSection.user_directory_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 16, 11, 23, 642825), verbose_name='When was this book published?'),
        ),
    ]
