# Generated by Django 3.2.7 on 2021-09-21 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_book_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsection',
            name='section_video_base',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 16, 43, 0, 47668), verbose_name='When was this book published?'),
        ),
    ]
