# Generated by Django 3.2.7 on 2021-09-21 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210921_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 16, 43, 16, 90479), verbose_name='When was this book published?'),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='section_video_base',
            field=models.CharField(max_length=300),
        ),
    ]
