# Generated by Django 3.2.7 on 2021-09-21 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210921_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 16, 54, 44, 533160), verbose_name='When was this book published?'),
        ),
    ]
