# Generated by Django 3.2.7 on 2021-09-21 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_book_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 17, 51, 23, 826648), verbose_name='When was this book published?'),
        ),
    ]
