# Generated by Django 3.2.7 on 2021-09-21 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_book_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 21, 33, 55, 917231), verbose_name='When was this book published?'),
        ),
    ]
