# Generated by Django 3.2.7 on 2021-09-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_book_book_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
